apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../../base/apps/organization-worker/
images:
- name: 485229547579.dkr.ecr.us-east-2.amazonaws.com/organization-worker
  newTag: 23169c189f9b45f57522823f021f864cea1551b9
