apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../../base/apps/organization-worker/
images:
- name: 751111534101.dkr.ecr.us-west-2.amazonaws.com/dotnetefcorewithsqs-worker
  newTag: 9013b3e53cba495a088f48b3fb06bd5e954217c6
