apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-worker
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: organization-worker
  template:
    metadata:
      labels:
        app: organization-worker
    spec:
      containers:
      - image: 485229547579.dkr.ecr.us-east-2.amazonaws.com/organization-worker:c207645ba59fb350b3586cafcbff628e037dc5ef
        name: organization-worker
        ports:
        - containerPort: 80
